### ISSUE TITLE
Some new ansi issues...

### ISSUE THREAD

**Issue by martykazmaier** [mkrueger/icy_term#38]
At least on my system (shsbbs.net) with ssh (login bbs password shsbbs).  I didn't check telnet.  The message/files groups/areas selector is off a bit and in ice edit, when wrapping, there is some weirdness.  I don't know how to be more precise, check it out on my system to see it.  Both of those problems didn't appear in netrunner or ftelnet.  I need to learn how to do video screen captures...

**Comment by mkrueger** [comment]
Seem to be fixed in one of my changes in the ansi backend.

I made an emergency release :) 
https://github.com/mkrueger/icy_term/releases/tag/0.6.5

I wanted to test some days the refactorings I did but my unit test coverage is good so at least some things are working :).
Nice that anyone uses IEMSI. Reopen if you still have issues with the selector.
