### ISSUE TITLE
New problem...

### ISSUE THREAD

**Issue by martykazmaier** [mkrueger/icy_term#75]
I've ran into this twice, and the only fix seems to be an uninstall and reinstall.  Upon opening icyterm, I'm not even given the option of doing anything. The screen just fills with repeating scrolling text.  It's a mess, but alt-x or alt-f4 get me out.

**Comment by mkrueger** [comment]
uninstall/reinstall should not alter anything because the options are stored independently of the installation in the config directory.

Is there anything to trigger that? May be an infinite loop with an error in one thread. I've refactored basically everything (sen/recv, sound, parsing etc.) is in an own thread could be that there is a loop somewhere I missed in the modelling.

**Comment by martykazmaier** [comment]
I think it was a video driver reinstall.
________________________________

**Comment by mkrueger** [comment]
That may be however I need a better/more robust rendering solution. But atm I'm a bit too lazy to learn wgpu - I should've chosen that from the beginning :(.
